- name: disable NetworkManager
  hosts: all
  become: yes

  tasks:
  - name: edit grub
    lineinfile:
      path: /etc/default/grub
      regexp: 'GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 elevator=noop crashkernel=auto net.ifnames=0 biosdevname=0"'
  
  - name: make grub
    command: grub2-mkconfig
