---

- name: install mariadb-server
  hosts: node1.example.com
  become: yes

  tasks:
  - name:  check file is exists
    stat:
      path: /tmp/database
    register: db

  - name: install mariadb-server
    package:
      name: mariadb-server
      state: latest
    when: db.stat.islnk is defined and db.stat.isreg

  - name: start mariadb-server
    service:
      name: mariadb
      state: started
      enabled: yes
