---

- name: install vsftpd
  hosts: node1.example.com
  become: yes
 
  tasks:
  - name: install vsftpd
    package:
      name: vsftpd
      state: latest

  - name: start vsftpd
    service:
      name: vsftpd
      state: started
      enabled: yes

  - name: open firewall
    firewalld:
      port: 21/tcp
      permanent: yes
      state: enabled
      immediate: yes

  - name: create dir
    file:
      path: /var/ftp/pub
      state: directory
      owner: ftp
      group: nobody
      mode: 0755
      setype: public_content_rw_t

  - name: set ftpd_anon_write
    seboolean:
      name: ftpd_anon_write
      state: yes
      persistent: yes

  - name: configure ftp
    lineinfile:
      dest: /etc/vsftpd/vsftpd.conf
      state: present
      regexp: 'anonymous_enable=NO'
      line: 'anonymous_enable=YES'

  - name: restart vsftpd
    service:
      name: vsftpd 
      state: restarted
